

export const NAV_TITLES: Record<string, string> = {
  '/dashboard': 'Dashboard',
  '/selecionar-empresa': 'Selecionar Empresa',
  '/selecionar-perfil': 'Selecionar Perfil',
  '/minha-empresa': 'Minha Empresa',
  '/fiscal': 'Lançamentos Fiscais',
  '/fiscal/orcamento': 'Orçamentos',
  '/fiscal/apuracao': 'Apuração de Impostos',
  '/fiscal/inventario': 'Inventário',
  '/fiscal/calculo-inventario': 'Cálculo de Inventário',
  '/pessoal': 'Central de Cálculos',
  '/pessoal/folha-de-pagamento': 'Folha de Pagamento',
  '/pessoal/rci': 'RCI (Pró-labore)',
  '/pessoal/13-salario': '13º Salário',
  '/pessoal/ferias': 'Férias',
  '/pessoal/rescisao': 'Rescisão',
  '/contabil/plano-de-contas': 'Plano de Contas',
  '/contabil/lancamentos': 'Lançamentos Contábeis (IA)',
  '/contabil/importacao-extrato': 'Importação de Extrato (IA)',
  '/contabil/relatorios-contabeis': 'Relatórios Contábeis',
  '/financeiro/contas-a-receber': 'Contas a Receber',
  '/financeiro/contas-a-pagar': 'Contas a Pagar',
  '/financeiro/fluxo-de-caixa': 'Fluxo de Caixa',
  '/cadastros': 'Cadastros',
  '/cadastros/parceiros': 'Parceiros',
  '/cadastros/funcionarios': 'Funcionários',
  '/cadastros/socios': 'Cadastro de Sócios',
  '/cadastros/produtos': 'Produtos',
  '/cadastros/servicos': 'Serviços',
  '/cadastros/aliquotas': 'Alíquotas',
  '/cadastros/rubricas': 'Rubricas',
  '/cadastros/cfop': 'CFOP',
  '/cadastros/natureza-operacao': 'Natureza da Operação',
  '/cadastros/tipo-negociacao': 'Tipos de Negociação',
  '/cadastros/unidade-de-medida': 'Unidades de Medida',
  '/cadastros/tabelas-cst': 'Tabelas CST/CSOSN',
  '/cadastros/tabela-ibge': 'Tabela IBGE',
  '/cadastros/historicos-contabeis': 'Históricos Contábeis',
  '/cadastros/indices': 'Índices Econômicos',
  '/cadastros/usuarios': 'Usuários e Perfis',
  '/parceiros': 'Parceiros',
  '/funcionarios': 'Funcionários',
  '/socios': 'Sócios',
  '/produtos': 'Produtos',
  '/servicos': 'Serviços',
  '/aliquotas': 'Alíquotas',
  '/rubricas': 'Rubricas',
  '/conectividade': 'Conectividade',
  '/relatorios': 'Central de Relatórios',
  '/utilitarios/eventos': 'Agenda de Eventos',
  '/utilitarios/arquivos': 'Arquivos',
  '/utilitarios/audit-trail': 'Trilha de Auditoria',
  '/utilitarios/gov-status': 'Status de Serviços do Governo',
  '/configuracoes': 'Configurações',
  '/admin': 'Painel de Administração',
};
